# Generated by Django 5.2.1 on 2025-05-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursodisciplina',
            options={'verbose_name': 'cursodisciplina', 'verbose_name_plural': 'cursosdisciplinas'},
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pessoa'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
