# Generated by Django 5.2.1 on 2025-05-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cursodisciplina_options_alter_ocorrencia_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursodisciplina',
            options={'verbose_name': 'Disciplina por Curso', 'verbose_name_plural': 'Disciplinas por Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='instituicao',
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao_ensino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição de Ensino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='instituicao_ensino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição de Ensino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areasaber',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Área do Saber'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.avaliacaotipo', verbose_name='Tipo de Avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='avaliacaotipo',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Tipo de Avaliação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='area_saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Área do Saber'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_total',
            field=models.IntegerField(verbose_name='Carga Horária Total (em horas)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao_meses',
            field=models.IntegerField(verbose_name='Duração (meses)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='area_saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Área do Saber'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Disciplina'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='numero_faltas',
            field=models.IntegerField(verbose_name='Número de Faltas'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_previsao_termino',
            field=models.DateField(verbose_name='Data de Previsão de Término'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da ocupação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ocupacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ocupacao', verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Turma'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Turno'),
        ),
    ]
